# Pandas Basics

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name" : ['aayush', 'harry', 'rohan','shubh'],
    "marks": [92,34,24,17],
    "city" : ['muzaffarpur','rampur','kolkata','antarctica']
}

In [3]:
df = pd.DataFrame(dict1)

# converted it into a table just like in excel

df

     name  marks         city
0  aayush     92  muzaffarpur
1   harry     34       rampur
2   rohan     24      kolkata
3   shubh     17   antarctica

In [4]:
# it identifies each row as index and each column with column_name

# if we want this dataframe to export it in csv/xlsx , then we will use to_csv function

df.to_csv('friends.csv')

# if we dont want the index column to be exported
df.to_csv('friends_IndexFalse.csv', index = False)

In [5]:
# if we want to see top/bottom 3 rows in the dataframe then,use head()/tail()

df.head(3)

     name  marks         city
0  aayush     92  muzaffarpur
1   harry     34       rampur
2   rohan     24      kolkata

In [6]:
df.tail(2)

    name  marks        city
2  rohan     24     kolkata
3  shubh     17  antarctica

In [7]:
# describe function gives statistical information about numerical columns

df.describe()

          marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [8]:
# importing a csv

data_csv = pd.read_csv('data.csv')

data_csv.head(3)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0

In [9]:
# to get particular column and the value on it (row,column)
fv = data_csv.at[0, 'Calories'].item()   # giving value on 0th index of column Calories
fv       # we use .item() as selecting a single numeric cell returns a NumPy scalar i.e np.float64 so converted it to float with .item

409.1

In [10]:
# to change the value of 0th index Maxpulse value
data_csv['Maxpulse'][0] = 131


data_csv.head(3)

/var/folders/dk/mlcg64md3_j_ggxlkxr4kxgr0000gn/T/ipykernel_34963/2786545842.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data_csv['Maxpulse'][0] = 131
/var/folders/dk/mlcg64md3_j_ggxlkxr4kxgr0000gn/T/ipykernel_34963/2786545842.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_csv['Maxpulse'][0] = 131

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       131     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0

In [11]:
# if we want to change the index of friends.csv

df.index = ['first','second','third','fourth']
df.to_csv('friends.csv')
df

          name  marks         city
first   aayush     92  muzaffarpur
second   harry     34       rampur
third    rohan     24      kolkata
fourth   shubh     17   antarctica

 Pandas is a  open source data analysis library written in python
 It leverages the power and speed of numpy to make data analysis and preprocessing easy for data scientists.
 it provides rich and highly robust data operations.

 Pandas has 2 types of DS :  

  a) Series    - It is a one dimensional aray with indexes
               - It stores a single column or row of data in a Dataframe
  b) Dataframe - It's tabular spreadsheet like structure representing rows
                 each of which contains one or multiple columns

 A 1D array(labeled) capable of holding any type of data - Series
 A 2D data (labeled) structure with columns of potentially different
    types of data - Dataframe

In [12]:
ser = pd.Series(np.random.rand(34))     # it will take 34 random values and insert into a 1D array

In [13]:
ser

0     0.260115
1     0.365752
2     0.942619
3     0.091671
4     0.625394
5     0.190900
6     0.468262
7     0.826356
8     0.789500
9     0.249287
10    0.455896
11    0.685363
12    0.976893
13    0.736397
14    0.762957
15    0.902827
16    0.617330
17    0.977268
18    0.888059
19    0.432818
20    0.697155
21    0.861542
22    0.359167
23    0.684239
24    0.556141
25    0.141962
26    0.035080
27    0.172552
28    0.994858
29    0.263038
30    0.107697
31    0.345260
32    0.923702
33    0.678497
dtype: float64

In [14]:
type(ser)     # series is a DS in pandas , just like DataFrame  which we already did in early of this file

pandas.core.series.Series

In [15]:
newdf = pd.DataFrame(np.random.rand(334,5))  # it means 334 rows and 5 columns

In [16]:
newdf.head()

          0         1         2         3         4
0  0.309499  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [17]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.309499  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [18]:
newdf.describe()        # statistics of the data

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.500020    0.472743    0.478851    0.496398    0.504446
std      0.275742    0.289724    0.282824    0.284366    0.285808
min      0.000879    0.003246    0.015680    0.003786    0.002936
25%      0.270086    0.219184    0.211266    0.249354    0.274165
50%      0.507158    0.459405    0.478538    0.498247    0.505881
75%      0.729204    0.733952    0.705233    0.724068    0.758934
max      0.999780    0.998227    0.998541    0.993901    0.993246

In [19]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [20]:
newdf[0][0] = "aayush"

/var/folders/dk/mlcg64md3_j_ggxlkxr4kxgr0000gn/T/ipykernel_34963/3402782624.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "aayush"
/var/folders/dk/mlcg64md3_j_ggxlkxr4kxgr0000gn/T/ipykernel_34963/3402782624.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'aayush' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "aayush"

In [21]:
newdf.dtypes     # datatype of first col changed to obj as there are 2 different DTypes now

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.head()

          0         1         2         3         4
0    aayush  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [23]:
#  printing index

newdf.index

RangeIndex(start=0, stop=334, step=1)

In [24]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [25]:
 # converting dataframe into numpy array - 

newdf.to_numpy()

array([['aayush', 0.24747486844864441, 0.5054529108006909,
        0.5697266535231497, 0.7909170878001698],
       [0.28440867023455463, 0.10985456148531259, 0.3160363775406396,
        0.7007454641301041, 0.1606097106416331],
       [0.8323560573221412, 0.05550082292032221, 0.4542098255318867,
        0.702655793398811, 0.1911082034149585],
       ...,
       [0.1175687919814985, 0.5511776439562145, 0.618121736573167,
        0.611460623481804, 0.47926309566375713],
       [0.1314858735689156, 0.5139084665040908, 0.8966929036464212,
        0.11834721519368951, 0.8316543578542211],
       [0.9414832009936313, 0.5386398528732464, 0.5952608454501028,
        0.7203218956469626, 0.6545255310842372]], dtype=object)

In [26]:
newdf[0][0] = 0.3

In [27]:
newdf.head()

          0         1         2         3         4
0       0.3  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [28]:
newdf.to_numpy()

array([[0.3, 0.24747486844864441, 0.5054529108006909, 0.5697266535231497,
        0.7909170878001698],
       [0.28440867023455463, 0.10985456148531259, 0.3160363775406396,
        0.7007454641301041, 0.1606097106416331],
       [0.8323560573221412, 0.05550082292032221, 0.4542098255318867,
        0.702655793398811, 0.1911082034149585],
       ...,
       [0.1175687919814985, 0.5511776439562145, 0.618121736573167,
        0.611460623481804, 0.47926309566375713],
       [0.1314858735689156, 0.5139084665040908, 0.8966929036464212,
        0.11834721519368951, 0.8316543578542211],
       [0.9414832009936313, 0.5386398528732464, 0.5952608454501028,
        0.7203218956469626, 0.6545255310842372]], dtype=object)

In [29]:
# to create Transpose of the current matrix

newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.284409,0.832356,0.925513,0.238217,0.680041,0.407362,0.498956,0.400055,0.080504,...,0.607722,0.166748,0.224196,0.10188,0.282337,0.718879,0.781429,0.117569,0.131486,0.941483
1,0.247475,0.109855,0.055501,0.829697,0.004381,0.475472,0.661065,0.828176,0.046673,0.228686,...,0.069285,0.229594,0.525921,0.089599,0.479953,0.043012,0.849501,0.551178,0.513908,0.53864
2,0.505453,0.316036,0.45421,0.500267,0.706809,0.926286,0.3034,0.116326,0.364178,0.336907,...,0.705306,0.652072,0.156818,0.466774,0.902287,0.251426,0.390789,0.618122,0.896693,0.595261
3,0.569727,0.700745,0.702656,0.045715,0.598162,0.549207,0.802173,0.558991,0.515407,0.355771,...,0.23797,0.012749,0.700484,0.915752,0.505966,0.023912,0.829368,0.611461,0.118347,0.720322
4,0.790917,0.16061,0.191108,0.978805,0.571063,0.00674,0.902178,0.45345,0.138393,0.807054,...,0.818011,0.892908,0.799883,0.744207,0.557503,0.247605,0.047553,0.479263,0.831654,0.654526

In [30]:
newdf.head()

          0         1         2         3         4
0       0.3  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [31]:
# reverse sort with index
# axis=0 means rows , ascending = False means in reverse order ; by default acending = True
newdf.sort_index(axis=0, ascending=False)     # by default axis = 0

            0         1         2         3         4
333  0.941483  0.538640  0.595261  0.720322  0.654526
332  0.131486  0.513908  0.896693  0.118347  0.831654
331  0.117569  0.551178  0.618122  0.611461  0.479263
330  0.781429  0.849501  0.390789  0.829368  0.047553
329  0.718879  0.043012  0.251426  0.023912  0.247605
..        ...       ...       ...       ...       ...
4    0.238217  0.004381  0.706809  0.598162  0.571063
3    0.925513  0.829697  0.500267  0.045715  0.978805
2    0.832356  0.055501  0.454210  0.702656  0.191108
1    0.284409  0.109855  0.316036  0.700745  0.160610
0         0.3  0.247475  0.505453  0.569727  0.790917

[334 rows x 5 columns]

In [32]:
# if we give axis = 1 , it will sort in column
newdf.sort_index(axis=1 , ascending=False)

            4         3         2         1         0
0    0.790917  0.569727  0.505453  0.247475       0.3
1    0.160610  0.700745  0.316036  0.109855  0.284409
2    0.191108  0.702656  0.454210  0.055501  0.832356
3    0.978805  0.045715  0.500267  0.829697  0.925513
4    0.571063  0.598162  0.706809  0.004381  0.238217
..        ...       ...       ...       ...       ...
329  0.247605  0.023912  0.251426  0.043012  0.718879
330  0.047553  0.829368  0.390789  0.849501  0.781429
331  0.479263  0.611461  0.618122  0.551178  0.117569
332  0.831654  0.118347  0.896693  0.513908  0.131486
333  0.654526  0.720322  0.595261  0.538640  0.941483

[334 rows x 5 columns]

In [33]:
# to everse-sort both rows and columns in one call

newdf.sort_index(ascending=False).sort_index(axis=1, ascending=False)

            4         3         2         1         0
333  0.654526  0.720322  0.595261  0.538640  0.941483
332  0.831654  0.118347  0.896693  0.513908  0.131486
331  0.479263  0.611461  0.618122  0.551178  0.117569
330  0.047553  0.829368  0.390789  0.849501  0.781429
329  0.247605  0.023912  0.251426  0.043012  0.718879
..        ...       ...       ...       ...       ...
4    0.571063  0.598162  0.706809  0.004381  0.238217
3    0.978805  0.045715  0.500267  0.829697  0.925513
2    0.191108  0.702656  0.454210  0.055501  0.832356
1    0.160610  0.700745  0.316036  0.109855  0.284409
0    0.790917  0.569727  0.505453  0.247475       0.3

[334 rows x 5 columns]

In [34]:
newdf.head()

          0         1         2         3         4
0       0.3  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [35]:
newdf2 = newdf

In [36]:
newdf2[0][0] = 9783

In [37]:
newdf2

            0         1         2         3         4
0        9783  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [38]:
newdf

            0         1         2         3         4
0        9783  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

 so changing newdf2 will also change newdf as newdf2 is a view of newdf
 and will point to same memory location

for copying , we have to write .copy()
then , if we do newdf3 = newdf and change something in newdf3 then it will not repliacate the same in newdf

In [39]:
newdf3 = newdf.copy()

newdf3[0][0] = 1234

newdf3

/var/folders/dk/mlcg64md3_j_ggxlkxr4kxgr0000gn/T/ipykernel_34963/1788979810.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 1234
/var/folders/dk/mlcg64md3_j_ggxlkxr4kxgr0000gn/T/ipykernel_34963/1788979810.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 1234

            0         1         2         3         4
0        1234  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [40]:
newdf

            0         1         2         3         4
0        9783  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

as shown, for newdf2[0][0] = 1234
whereas newdf[0][0] = 9783

In [41]:
# to assign something its better to use loc(row,column) function rather than [i][j]
newdf.loc[0,0] = 654

newdf.head()

          0         1         2         3         4
0       654  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063

In [42]:

newdf

            0         1         2         3         4
0         654  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [43]:
newdf.columns = ["A", "B", "C", "D", "E"]

In [44]:
newdf

            A         B         C         D         E
0         654  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [45]:
# newdf.loc[0,0]  = 432

newdf # it willn't change as now column has been changed to abcde

            A         B         C         D         E
0         654  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [46]:
newdf.loc[0,'A'] = 313


newdf

            A         B         C         D         E
0         313  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [47]:
# to delete a column
# newdf = newdf.drop(0, axis=1)         #axis = 1 means column so it drop it from the columns

In [48]:
newdf

            A         B         C         D         E
0         313  0.247475  0.505453  0.569727  0.790917
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[334 rows x 5 columns]

In [49]:
# to get a set of columns

newdf.loc[[1,2],['C','D']]       # returning a new dataframe and not changing original

          C         D
1  0.316036  0.700745
2  0.454210  0.702656

In [50]:
 # to want all the rows
newdf.loc[:,['C','D']]  # gives all rows

            C         D
0    0.505453  0.569727
1    0.316036  0.700745
2    0.454210  0.702656
3    0.500267  0.045715
4    0.706809  0.598162
..        ...       ...
329  0.251426  0.023912
330  0.390789  0.829368
331  0.618122  0.611461
332  0.896693  0.118347
333  0.595261  0.720322

[334 rows x 2 columns]

In [51]:
 # to want all the columns
newdf.loc[[1,2],:]  # gives all rows

          A         B         C         D         E
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108

In [52]:
# to run complex queries

newdf.loc[(newdf['A']<0.3)]     # will return those columns where the exp value matches

            A         B         C         D         E
1    0.284409  0.109855  0.316036  0.700745  0.160610
4    0.238217  0.004381  0.706809  0.598162  0.571063
9    0.080504  0.228686  0.336907  0.355771  0.807054
10   0.297108  0.738840  0.913634  0.422853  0.479293
14   0.257842  0.933879  0.312460  0.297835  0.838588
..        ...       ...       ...       ...       ...
326  0.224196  0.525921  0.156818  0.700484  0.799883
327   0.10188  0.089599  0.466774  0.915752  0.744207
328  0.282337  0.479953  0.902287  0.505966  0.557503
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654

[97 rows x 5 columns]

In [53]:
newdf.loc[(newdf['A']<0.3) &  (newdf['C']> 0.1)]

            A         B         C         D         E
1    0.284409  0.109855  0.316036  0.700745  0.160610
4    0.238217  0.004381  0.706809  0.598162  0.571063
9    0.080504  0.228686  0.336907  0.355771  0.807054
10   0.297108  0.738840  0.913634  0.422853  0.479293
14   0.257842  0.933879  0.312460  0.297835  0.838588
..        ...       ...       ...       ...       ...
326  0.224196  0.525921  0.156818  0.700484  0.799883
327   0.10188  0.089599  0.466774  0.915752  0.744207
328  0.282337  0.479953  0.902287  0.505966  0.557503
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654

[86 rows x 5 columns]

In [54]:
# iloc features

newdf.head(6)

          A         B         C         D         E
0       313  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108
3  0.925513  0.829697  0.500267  0.045715  0.978805
4  0.238217  0.004381  0.706809  0.598162  0.571063
5  0.680041  0.475472  0.926286  0.549207  0.006740

In [55]:
newdf.iloc[0,4].item()    # if we want using index name, use loc , else use iloc

0.7909170878001698

In [56]:
newdf.iloc[[0,5], [1,2]]

          B         C
0  0.247475  0.505453
5  0.475472  0.926286

In [57]:
newdf.head(3)

          A         B         C         D         E
0       313  0.247475  0.505453  0.569727  0.790917
1  0.284409  0.109855  0.316036  0.700745  0.160610
2  0.832356  0.055501  0.454210  0.702656  0.191108

In [58]:
newdf.drop([0])       # dropping a row from the copy written

            A         B         C         D         E
1    0.284409  0.109855  0.316036  0.700745  0.160610
2    0.832356  0.055501  0.454210  0.702656  0.191108
3    0.925513  0.829697  0.500267  0.045715  0.978805
4    0.238217  0.004381  0.706809  0.598162  0.571063
5    0.680041  0.475472  0.926286  0.549207  0.006740
..        ...       ...       ...       ...       ...
329  0.718879  0.043012  0.251426  0.023912  0.247605
330  0.781429  0.849501  0.390789  0.829368  0.047553
331  0.117569  0.551178  0.618122  0.611461  0.479263
332  0.131486  0.513908  0.896693  0.118347  0.831654
333  0.941483  0.538640  0.595261  0.720322  0.654526

[333 rows x 5 columns]

In [59]:
newdf.drop(['A','C'], axis=1)       # dropping a column from the copy written , if want to change in original file , newdf = newdf.drop(['A','C'], axis=1)

            B         D         E
0    0.247475  0.569727  0.790917
1    0.109855  0.700745  0.160610
2    0.055501  0.702656  0.191108
3    0.829697  0.045715  0.978805
4    0.004381  0.598162  0.571063
..        ...       ...       ...
329  0.043012  0.023912  0.247605
330  0.849501  0.829368  0.047553
331  0.551178  0.611461  0.479263
332  0.513908  0.118347  0.831654
333  0.538640  0.720322  0.654526

[334 rows x 3 columns]

In [60]:
# using inplace = true, we can made changes too in original file
newdf.drop(['A','C'], axis=1, inplace=True)

In [61]:
newdf

            B         D         E
0    0.247475  0.569727  0.790917
1    0.109855  0.700745  0.160610
2    0.055501  0.702656  0.191108
3    0.829697  0.045715  0.978805
4    0.004381  0.598162  0.571063
..        ...       ...       ...
329  0.043012  0.023912  0.247605
330  0.849501  0.829368  0.047553
331  0.551178  0.611461  0.479263
332  0.513908  0.118347  0.831654
333  0.538640  0.720322  0.654526

[334 rows x 3 columns]

In [62]:
newdf.drop([1,5], axis=0, inplace=True)

In [63]:
newdf.head(5)

          B         D         E
0  0.247475  0.569727  0.790917
2  0.055501  0.702656  0.191108
3  0.829697  0.045715  0.978805
4  0.004381  0.598162  0.571063
6  0.661065  0.802173  0.902178

In [64]:
# if we want the row index to arrange ; must add drop=true, otherwise it will add a new column unnecesarily
newdf.reset_index(drop=True)

            B         D         E
0    0.247475  0.569727  0.790917
1    0.055501  0.702656  0.191108
2    0.829697  0.045715  0.978805
3    0.004381  0.598162  0.571063
4    0.661065  0.802173  0.902178
..        ...       ...       ...
327  0.043012  0.023912  0.247605
328  0.849501  0.829368  0.047553
329  0.551178  0.611461  0.479263
330  0.513908  0.118347  0.831654
331  0.538640  0.720322  0.654526

[332 rows x 3 columns]

In [65]:
# how to remove duplicates from a dataframe

newdf['B'].isnull()      # returns True is any value in a column is null

0      False
2      False
3      False
4      False
6      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 332, dtype: bool

In [66]:
# to make every value in a column as null

newdf['B'] = None

In [67]:
newdf

        B         D         E
0    None  0.569727  0.790917
2    None  0.702656  0.191108
3    None  0.045715  0.978805
4    None  0.598162  0.571063
6    None  0.802173  0.902178
..    ...       ...       ...
329  None  0.023912  0.247605
330  None  0.829368  0.047553
331  None  0.611461  0.479263
332  None  0.118347  0.831654
333  None  0.720322  0.654526

[332 rows x 3 columns]

In [68]:
newdf.isnull()

        B      D      E
0    True  False  False
2    True  False  False
3    True  False  False
4    True  False  False
6    True  False  False
..    ...    ...    ...
329  True  False  False
330  True  False  False
331  True  False  False
332  True  False  False
333  True  False  False

[332 rows x 3 columns]

In [69]:
newdf

        B         D         E
0    None  0.569727  0.790917
2    None  0.702656  0.191108
3    None  0.045715  0.978805
4    None  0.598162  0.571063
6    None  0.802173  0.902178
..    ...       ...       ...
329  None  0.023912  0.247605
330  None  0.829368  0.047553
331  None  0.611461  0.479263
332  None  0.118347  0.831654
333  None  0.720322  0.654526

[332 rows x 3 columns]

In [70]:
newdf['B'] = 34

In [71]:
newdf

      B         D         E
0    34  0.569727  0.790917
2    34  0.702656  0.191108
3    34  0.045715  0.978805
4    34  0.598162  0.571063
6    34  0.802173  0.902178
..   ..       ...       ...
329  34  0.023912  0.247605
330  34  0.829368  0.047553
331  34  0.611461  0.479263
332  34  0.118347  0.831654
333  34  0.720322  0.654526

[332 rows x 3 columns]

In [72]:
# creating a new df

df = pd.DataFrame({
    "name" : ['Alfred', 'Batman', 'Alfred'],
    "toy" : [np.nan, 'Batmobile', 'Bullwhip'],
    "born" : [pd.NaT , pd.Timestamp("1940-04-25"), pd.NaT]
})

In [73]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [74]:
# df.dropna()       # it will drop wherever Na is mentioned

In [75]:
# df.dropna(how='all', axis=1) # it will remove only if all rows for the col is Na , given axis=1 for column

In [76]:
# to remove duplicates

df.drop_duplicates(subset=['name'])     # it will remove the duplicates from name column

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25

In [77]:
# if we want 1st occurence and want to remove others,
df.drop_duplicates(subset=['name'], keep='first')

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25

In [78]:
# if we want last occurence and want to remove others,
df.drop_duplicates(subset=['name'], keep='last')

     name        toy       born
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [79]:
#  inspect a dataset

df.shape

(3, 3)

In [80]:
df.info()      # will tell the class, rangeIndex, data columns , DT, memory usages

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [81]:
# to get unique values count
df['toy'].value_counts(dropna=False)

toy
NaN          1
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [82]:
# it will tell whether null is  not there or is it
# it is reverse of isnull()
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

In [83]:
import pandas as pd
import numpy as np

# create a df which contains only int with 3 rows and 2 columns

df1 = pd.DataFrame(np.random.randint(0, 100, size=(3, 2)))

In [84]:
df1

    0   1
0  28  69
1  97  67
2  97  16

In [85]:
df1.describe()

               0          1
count   3.000000   3.000000
mean   74.000000  50.666667
std    39.837169  30.038864
min    28.000000  16.000000
25%    62.500000  41.500000
50%    97.000000  67.000000
75%    97.000000  68.000000
max    97.000000  69.000000

In [86]:
df1.mean()

0    74.000000
1    50.666667
dtype: float64

In [87]:
df1.corr()

          0         1
0  1.000000 -0.528553
1 -0.528553  1.000000

In [88]:
df1.count()

0    3
1    3
dtype: int64

In [89]:
df1.max()

0    97
1    69
dtype: int64

In [90]:
df1.min()

0    28
1    16
dtype: int64

In [92]:
df1.median()

0    97.0
1    67.0
dtype: float64

In [ ]:
df1.std()     # returns standard deviation

0    39.837169
1    30.038864
dtype: float64

In [103]:
 # handle excel sheet with pandas read_excel and specific sheet

data = pd.read_excel('data.xlsx', sheet_name='Sheet2')

In [97]:
data

   TrainNo2  Speed2       City2
0     12322      50      Rampur
1     12342     123     Kolkata
2    125654      54    bareilly
3    564528      43  antarctica

In [98]:
#  to write in sheet2

data.iloc[0,0] = 34

In [99]:
data

   TrainNo2  Speed2       City2
0        34      50      Rampur
1     12342     123     Kolkata
2    125654      54    bareilly
3    564528      43  antarctica

In [100]:
data.to_excel('data.xlsx', sheet_name='Sheet2')

In [101]:
data

   TrainNo2  Speed2       City2
0        34      50      Rampur
1     12342     123     Kolkata
2    125654      54    bareilly
3    564528      43  antarctica

In [ ]:
data = pd.read_excel('data.xlsx', sheet_name='Sheet1')     # ValueError: Worksheet named 'Sheet1' not found as it removes the sheet 1

ValueError: Worksheet named 'Sheet1' not found

In [104]:
data1 = data.copy()
with pd.ExcelWriter('data.xlsx') as writer:
    data.to_excel(writer, sheet_name='Sheet1')
    data1.to_excel(writer, sheet_name='Sheet1')

this is how we have to write in excel using ExcelWriter function